services:
  # Next.js web app for development with HMR
  web-dev:
    container_name: ${COMPOSE_PROJECT_NAME:-nextjs-directus}-web-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web.dev
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - NODE_ENV=development
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8055/}
        - NEXT_PUBLIC_API_PORT=${NEXT_PUBLIC_API_PORT:-8055}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
        - NEXT_PUBLIC_APP_PORT=${NEXT_PUBLIC_APP_PORT:-3000}
        - API_PING_PATH=${API_PING_PATH:-/server/health}
        - API_ADMIN_TOKEN=${API_ADMIN_TOKEN:-secret-admin-token}
        - AUTH_SECRET=${AUTH_SECRET:-QgafJQw3O/k1gambz7YGKjtj5ZZe0dnL/WlSw4PtMDc=}
    restart: unless-stopped
    ports:
      - "${NEXT_PUBLIC_APP_PORT:-3000}:${NEXT_PUBLIC_APP_PORT:-3000}"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    environment:
      - NODE_ENV=development
      - API_PING_PATH=/server/health
      # Server-side API URL (external API server)
      - API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8055}
      # Client-side API URL (localhost for browser)
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8055}
      - NEXT_PUBLIC_API_PORT=${NEXT_PUBLIC_API_PORT:-8055}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - NEXT_PUBLIC_APP_PORT=${NEXT_PUBLIC_APP_PORT:-3000}
      - API_ADMIN_TOKEN=${API_ADMIN_TOKEN:-secret-admin-token}
      - AUTH_SECRET=${AUTH_SECRET:-QgafJQw3O/k1gambz7YGKjtj5ZZe0dnL/WlSw4PtMDc=}
      # Enable hot reloading
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      # Development specific settings
      - NEXT_TELEMETRY_DISABLED=1
      - MILLION_LINT=false
      - REACT_SCAN=false
      - SHOW_AUTH_LOGS=true
      - NEXT_PUBLIC_SHOW_AUTH_LOGS=true
    # Use host networking to easily connect to external API
    network_mode: host
