services:
  api-db:
    extends:
      file: ./apps/api/docker-compose.yml
      service: api-db
    volumes:
      - api_db_data:/var/lib/mysql
    networks:
      - app_network

  api-cache:
    extends:
      file: ./apps/api/docker-compose.yml
      service: api-cache
    networks:
      - app_network

  api:
    extends:
      file: ./apps/api/docker-compose.yml
      service: api
    depends_on:
      api-db:
        condition: service_healthy
      api-cache:
        condition: service_healthy
    environment:
      ADMIN_TOKEN: ${API_ADMIN_TOKEN:-secret-admin-token}

    networks:
      - app_network

networks:
  app_network:
    # bridge
    driver: bridge

volumes:
  api_db_data:
