services:
  # Database for API
  api-db-prod:
    container_name: ${COMPOSE_PROJECT_NAME:-nextjs-directus}-api-db-prod
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-nestjs_api}
    volumes:
      - api_db_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_DATABASE:-nestjs_api}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api_network_prod

  # Redis cache for API
  api-cache-prod:
    container_name: ${COMPOSE_PROJECT_NAME:-nextjs-directus}-api-cache-prod
    image: redis:8-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    networks:
      - api_network_prod

  # NestJS API service
  api-prod:
    container_name: ${COMPOSE_PROJECT_NAME:-nextjs-directus}-api-prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api.prod
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
        - API_PORT=${API_PORT:-3001}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
        - API_PING_PATH=${API_PING_PATH:-/health}
    depends_on:
      api-db-prod:
        condition: service_healthy
      api-cache-prod:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "${API_PORT:-3001}:${API_PORT:-3001}"
    environment:
      NODE_ENV: production
      API_PORT: ${API_PORT:-3001}
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@api-db-prod:5432/${DB_DATABASE:-nestjs_api}
      REDIS_URL: redis://api-cache-prod:6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      AUTH_SECRET: ${AUTH_SECRET:-QgafJQw3O/k1gambz7YGKjtj5ZZe0dnL/WlSw4PtMDc=}
      NEXT_PUBLIC_WEB_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      # CORS Configuration for cross-origin requests from web app
      CORS_ORIGIN: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      # Production optimizations
      LOG_LEVEL: warn
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:${API_PORT:-3001}/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 5
    networks:
      - api_network_prod

networks:
  api_network_prod:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-directus}_api_network_prod
    driver: bridge

volumes:
  api_db_data_prod:
    name: ${COMPOSE_PROJECT_NAME:-nextjs-directus}_api_db_data_prod
