[build]
base = "apps/api"
publish = "public"  # Or the directory where your built assets are
command = "docker compose --build"

[dev]
command = "docker compose up"
port = 8055 # Or the port your application listens on
targetPort = 8055 # The port exposed by your Docker container
publish = "public"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200