// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod'
import { makeGetRoute, makePostRoute, makeRoute } from './makeRoute'

const defaultInfo = {
    search: z.object({}),
}

import * as HomeRoute from '@/app/page.info'
import * as MiddlewareerrorenvRoute from '@/app/(internal)/middleware/error/env/page.info'
import * as MiddlewareerrorhealthCheckRoute from '@/app/(internal)/middleware/error/healthCheck/page.info'
import * as ApiauthnextauthRoute from '@/app/api/auth/[...nextauth]/route.info'
import * as ApiauthrefreshtokenRoute from '@/app/api/auth/refresh_token/route.info'
import * as ApisentryExampleApiRoute from '@/app/api/sentry-example-api/route.info'
import * as AutherrorRoute from '@/app/auth/error/page.info'
import * as AuthloginRoute from '@/app/auth/login/page.info'
import * as AuthmeRoute from '@/app/auth/me/page.info'
import * as AppshowcaseRoute from '@/app/showcase/page.info'
import * as AppshowcaseClientRoute from '@/app/showcase/client/page.info'
import * as AppshowcaseServerRoute from '@/app/showcase/server/page.info'

export const Home = makeRoute('/', {
    ...defaultInfo,
    ...HomeRoute.Route,
})
export const Middlewareerrorenv = makeRoute(
    '/(internal)/middleware/error/env',
    {
        ...defaultInfo,
        ...MiddlewareerrorenvRoute.Route,
    }
)
export const MiddlewareerrorhealthCheck = makeRoute(
    '/(internal)/middleware/error/healthCheck',
    {
        ...defaultInfo,
        ...MiddlewareerrorhealthCheckRoute.Route,
    }
)
export const Apiauthnextauth = makeRoute('/api/auth/[...nextauth]', {
    ...defaultInfo,
    ...ApiauthnextauthRoute.Route,
})
export const Autherror = makeRoute('/auth/error', {
    ...defaultInfo,
    ...AutherrorRoute.Route,
})
export const Authlogin = makeRoute('/auth/login', {
    ...defaultInfo,
    ...AuthloginRoute.Route,
})
export const Authme = makeRoute('/auth/me', {
    ...defaultInfo,
    ...AuthmeRoute.Route,
})
export const Appshowcase = makeRoute('/showcase', {
    ...defaultInfo,
    ...AppshowcaseRoute.Route,
})
export const AppshowcaseClient = makeRoute('/showcase/client', {
    ...defaultInfo,
    ...AppshowcaseClientRoute.Route,
})
export const AppshowcaseServer = makeRoute('/showcase/server', {
    ...defaultInfo,
    ...AppshowcaseServerRoute.Route,
})

export const postApiauthrefreshtoken = makePostRoute(
    '/api/auth/refresh_token',
    {
        ...defaultInfo,
        ...ApiauthrefreshtokenRoute.Route,
    },
    ApiauthrefreshtokenRoute.POST
)
export const getApisentryExampleApi = makeGetRoute(
    '/api/sentry-example-api',
    {
        ...defaultInfo,
        ...ApisentryExampleApiRoute.Route,
    },
    ApisentryExampleApiRoute.GET
)
