FROM node:18-alpine AS base

# This Dockerfile is copy-pasted into our main docs at /docs/handbook/deploying-with-docker.
# Make sure you update both files!

FROM base AS builder
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk update
RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app
COPY . .
RUN npx turbo prune web --docker

# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app

# First install the dependencies (as they change less often)
COPY --from=builder /app/out/json/ .
RUN npm install

# Build the project
COPY --from=builder /app/out/full/ .

# API_PING_PATH: /server/ping
#       NEXT_PUBLIC_APP_DIRECTUS_PROXY_PATH: /api/_directus
#       NEXT_PUBLIC_API_URL: http://localhost:8055
#       NEXT_PUBLIC_API_PORT: 8055
#       NEXT_PUBLIC_APP_URL: http://localhost:3000
#       NEXT_PUBLIC_APP_PORT: 3000
#       API_ADMIN_TOKEN: ${API_ADMIN_TOKEN:-secret-admin-token}

ARG API_PING_PATH
ENV API_PING_PATH=$API_PING_PATH

ARG NEXT_PUBLIC_APP_DIRECTUS_PROXY_PATH
ENV NEXT_PUBLIC_APP_DIRECTUS_PROXY_PATH=$NEXT_PUBLIC_APP_DIRECTUS_PROXY_PATH

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

ARG NEXT_PUBLIC_API_PORT
ENV NEXT_PUBLIC_API_PORT=$NEXT_PUBLIC_API_PORT

ARG NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

ARG NEXT_PUBLIC_APP_PORT
ENV NEXT_PUBLIC_APP_PORT=$NEXT_PUBLIC_APP_PORT

ARG API_ADMIN_TOKEN
ENV API_ADMIN_TOKEN=$API_ADMIN_TOKEN

ARG AUTH_SECRET
ENV AUTH_SECRET=$AUTH_SECRET

# ARG TURBO_TEAM
# ENV TURBO_TEAM=$TURBO_TEAM

# ARG TURBO_TOKEN
# ENV TURBO_TOKEN=$TURBO_TOKEN

RUN wget $NEXT_PUBLIC_API_URL$API_PING_PATH && sleep 10

RUN npx turbo build

FROM base AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalon[e] ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.env.local ./apps/web/.env.local

CMD node apps/web/server.js